version: 2

sources:
  - name: public             # schema name 
    database: warehouse      #  database name
    tables:
      - name: customers
        description: "Raw customer master"
        columns:
          - name: id
            description: "Primary key for customer"
            tests: [not_null, unique]
          - name: email
            description: "Email address"
            tests: [not_null, unique]

      - name: products
        description: "Product catalog"
        columns:
          - name: id
            description: "Product ID"
            tests: [not_null, unique]
          - name: price_gbp
            description: "Price in GBP"
            tests: [not_null]

      - name: transactions
        description: "Transaction fact table"
        columns:
          - name: id
            tests: [not_null, unique]
          - name: customer_id
            tests:
              - not_null
              - relationships:
                  to: ref('stg_customers')
                  field: customer_id
          - name: product_id
            tests:
              - not_null
              - relationships:
                  to: ref('stg_products')
                  field: product_id
